### ISSUE TITLE
Debug RRWeb styleSheetObserver exception

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry-replay#297]
```
TypeError: Cannot read properties of undefined (reading 'prototype')
  at styleSheetObserver(webpack://frontend/../node_modules/rrweb/es/rrweb/packages/rrweb/src/record/observer.js:382:27)
  at h(webpack://frontend/../node_modules/rrweb/es/rrweb/packages/rrweb/src/record/observer.js:657:9)
  at ? (webpack://frontend/../node_modules/rrweb/es/rrweb/packages/rrweb/src/record/index.js:348:54)
  at Array.forEach(<anonymous>)
  at stopRecording(webpack://frontend/../node_modules/rrweb/es/rrweb/packages/rrweb/src/record/index.js:348:24)
  at pause(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:1372:18)
  at checkAndHandleExpiredSession(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:1716:18)
  at call(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:1203:35)
  at step(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:76:23)
  at next(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:57:53)
  at ? (webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:50:71)
  at new Promise(<anonymous>)
  at __awaiter(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:46:12)
  at flush(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:1192:43)
  at apply(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:1283:67)
  at invokeFunc(webpack://frontend/../node_modules/lodash.debounce/index.js:160:19)
  at trailingEdge(webpack://frontend/../node_modules/lodash.debounce/index.js:207:14)
  at flush(webpack://frontend/../node_modules/lodash.debounce/index.js:222:45)
  at flushImmediate(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:1838:36)
  at call(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:1011:63)
  at step(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:76:23)
  at next(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:57:53)
  at ? (webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:50:71)
  at new Promise(<anonymous>)
  at __awaiter(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:46:12)
  at apply(webpack://frontend/../node_modules/@sentry/replay/dist/index.es.js:1008:49)
  at n(webpack://frontend/../node_modules/@sentry/browser/esm/helpers.js:90:17)
```

**Comment by billyvg** [comment]
It's possible this could be related to the Styled Components library

**Comment by billyvg** [comment]
From what I could tell, it was not browser/platform related

**Comment by billyvg** [comment]
This will no longer blow up thanks to #315, but I'm still curious about what's going on. Since this seems to only happen when we stop a recording, I suspect there's a leak somewhere and some CSS changes are still being observed after we stop the recording.

**Comment by ryan953** [comment]
We've caught some examples of this happeneing on sentry.io: https://sentry.io/organizations/sentry/issues/3726767539/events/bab3cf9112384fd8b2d940899066a0d9/?project=11276

it's happened for a small number of people, but one person has figured out how to trigger it hundreds of times.

**Comment by erictaylor** [comment]
Not sure if this is helpful, but we were seeing this error when Android users were loading our application via in-app browsers (such as Instagram, Snapchat, etc. when "sharing").

**Comment by ryan953** [comment]
This could also be related to a `Permission denied to access property "CSSStyleSheet" on cross-origin object` error we've been seeing a lot of:
https://sentry.io/organizations/sentry/issues/3755542796/?query=CSSStyleSheet&referrer=issue-stream&statsPeriod=14d
